"""Machine-readable errors used by the multi-Agent runtime.
多 Agent 运行时使用的机器可读错误码。
"""

from enum import Enum


class ErrorCode(str, Enum):
    """Stable error codes for persisted events and recovery decisions.
    用于持久化事件和恢复决策的稳定错误码。
    """

    QWEN_UNREACHABLE = "QWEN_UNREACHABLE"
    QWEN_TIMEOUT = "QWEN_TIMEOUT"
    QWEN_EMPTY_RESPONSE = "QWEN_EMPTY_RESPONSE"
    QWEN_INVALID_JSON = "QWEN_INVALID_JSON"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    TILE_COUNT_MISMATCH = "TILE_COUNT_MISMATCH"
    POINT_OUTSIDE_CORE = "POINT_OUTSIDE_CORE"
    TILE_RECURSION_LIMIT = "TILE_RECURSION_LIMIT"
    SEAM_UNRESOLVED = "SEAM_UNRESOLVED"
    DEEPSEEK_UNREACHABLE = "DEEPSEEK_UNREACHABLE"
    DEEPSEEK_EMPTY_JSON = "DEEPSEEK_EMPTY_JSON"
    DATA_IMAGE_MISSING = "DATA_IMAGE_MISSING"
    DATA_RECORD_INVALID = "DATA_RECORD_INVALID"
    RUN_BUDGET_EXCEEDED = "RUN_BUDGET_EXCEEDED"
